# Generated by Django 4.2.14 on 2024-08-09 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("developers", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(name="developer", table="developers",),
    ]
